import Head from "next/head";
import { FunctionComponent } from "react";
import { useState } from "react";
import { PersoInfo } from "../modules/form/screen";

export default function Home() {
  const [selectedStep, setSelectedStep] = useState<number>(1);
  interface NavItemProps {
    name: string;
    stepNumber: number;
  }

  const NavItem: FunctionComponent<NavItemProps> = ({ name, stepNumber }) => {
    const isSelected = selectedStep === stepNumber;

    return (
      <div className="flex" onClick={() => setSelectedStep(stepNumber)}>
        <h1>{stepNumber}</h1>
        <div>
          <p>STEP {stepNumber}</p>
          <h2>{name}</h2>
        </div>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center min-h-screen">
        <div className="flex justify-between items-center w-[90%] max-w-800px] m-auto">
          <nav>
            <ol>
              <li>
                <NavItem name="your Info" stepNumber={1} />
              </li>
              <li>
                <NavItem name="Select Plan" stepNumber={2} />
              </li>
              <li>
                <NavItem name="your Info" stepNumber={3} />
              </li>
              <li>
                <NavItem name="Summary" stepNumber={4} />
              </li>
            </ol>
          </nav>
          <main>
            {selectedStep === 1 && <PersoInfo />}
            {selectedStep === 2 && <p>2</p>}
            {selectedStep === 3 && <p>3</p>}
            {selectedStep === 4 && <p>4</p>}
          </main>
        </div>
      </div>
    </>
  );
}
